const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync,existsSync}=require('node:fs');
const {createContext,runInContext}=require('node:vm');
const fixture=()=>({revision:1,companies:[],student:{stage:'',skills:'',projects:'',roles:'',locations:''},jobs:[],updates:[],usage:{rows:[],asOf:'',version:'',startDate:'',endDate:'',fetchedAt:'',sourceUrl:''},advice:[],keyConfigured:false});
function harness(){
  const nodes=new Map(),requests=[],copied=[];
  const node=(tag='div')=>({tagName:tag.toUpperCase(),value:'',checked:false,disabled:false,hidden:false,open:false,textContent:'',children:[],handlers:{},dataset:{},attributes:{},classList:{toggle(){}},append(...x){this.children.push(...x);},replaceChildren(...x){this.children=x;},setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,fn){this.handlers[k]=fn;},focus(){this.focusCalls=(this.focusCalls||0)+1;this.focusedWhileDisabled=this.disabled;},showModal(){this.open=true;},close(){this.open=false;},querySelector(){return null;}});
  for(const m of readFileSync('internal/app/web/index.html','utf8').matchAll(/id="([^"]+)"/g))nodes.set(m[1],node());
  const document={createElement:node,createTextNode:t=>({textContent:t}),getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},activeElement:node()};
  let settings={provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'local',localConfirmed:true};
  const context=createContext({window:{},document,URL,AbortController,Date,Set,Map,navigator:{clipboard:{writeText:async t=>copied.push(t)}}});
  if(existsSync('internal/app/web/career.js'))runInContext(readFileSync('internal/app/web/career.js','utf8'),context);
  const career=context.window.AIviaCareer;
  assert.ok(career,'Career Radar must expose its deferred initializer');
  const api=(url,method='GET',body,signal)=>new Promise((resolve,reject)=>requests.push({url,method,body,signal,resolve,reject}));
  career.init({api,el:(tag,text,cls)=>{const n=node(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;},settings:()=>settings});
  document.activeElement=nodes.get('career-add-company');
  return {career,nodes,requests,copied,setSettings:v=>settings=v};
}
const all=n=>[n,...(n.children||[]).flatMap(all)];
const text=n=>all(n).map(x=>x.textContent).join('\n');
const click=async(n)=>{const fn=n.onclick||n.handlers.click;assert.ok(fn,'Expected wired action');return fn({preventDefault(){}});};
const input=n=>(n.oninput||n.onchange||n.handlers.change)();
async function loaded(f=fixture()){const h=harness();assert.equal(h.requests.length,0);const p=h.career.enter();h.requests[0].resolve(f);await p;return h;}
const company={id:'c1',name:'Synthetic AI',website:'https://example.com/',careersUrl:'https://jobs.ashbyhq.com/example',newsUrls:[],modelPrefixes:[],refreshes:[]};
const job=(id,extra={})=>({id,companyId:'c1',provider:'paste',providerId:id,sourceUrl:'',url:'https://example.com/job',title:'Software internship',location:'London',workplace:'remote',employmentType:'unknown',text:'Authored example',level:'internship',levelBasis:'title-inferred',publishedAt:'',updatedAt:'',dateBasis:'unknown',fetchedAt:'2026-10-01T00:00:00Z',listingState:'unknown',truncated:false,...extra});
const preview={revision:1,messages:[{role:'system',content:'Exact system'},{role:'user',content:'Exact reviewed context'}],hash:'preview-1',sources:[],settings:{provider:'ollama',endpoint:'http://127.0.0.1:11434',model:'local',localConfirmed:true},delivery:'direct'};
async function makePreview(h,p=preview){const pending=click(h.nodes.get('career-preview'));h.requests.at(-1).resolve(p);await pending;}

test('initialization sends nothing; entry reads only local Career state',async()=>{const h=await loaded();assert.deepEqual(h.requests.map(r=>r.url),['/api/career']);assert.ok(h.requests.every(r=>r.method==='GET'));});
test('company save blocks duplicate submissions and preserves draft on failure',async()=>{const h=await loaded();await click(h.nodes.get('career-add-company'));h.nodes.get('career-company-name').value='Draft';const p=click(h.nodes.get('career-company-save')),q=click(h.nodes.get('career-company-save'));assert.equal(h.requests.length,2);assert.equal(h.requests[1].method,'POST');h.requests[1].reject(new Error('Conflict'));await p;await q;assert.equal(h.nodes.get('career-company-name').value,'Draft');assert.match(text(h.nodes.get('career-status')),/Conflict/);assert.match(text(h.nodes.get('career-company-status') || {children:[],textContent:''}),/Conflict/);const retry=click(h.nodes.get('career-company-save'));h.requests.at(-1).resolve({...fixture(),revision:2,companies:[company]});await retry;});
test('navigation aborts pending local reads and discards a late response',async()=>{const h=harness();const p=h.career.enter();h.career.leave();assert.equal(h.requests[0].signal.aborted,true);h.requests[0].resolve({...fixture(),companies:[company]});await p;assert.doesNotMatch(text(h.nodes.get('career-companies')),/Synthetic AI/);});
test('changed selection and settings invalidate preview and discard late analysis',async()=>{const f=fixture();f.companies=[company];f.jobs=[job('j1')];const h=await loaded(f);await makePreview(h);assert.equal(h.nodes.get('career-analyze').disabled,true);h.nodes.get('career-send-consent').checked=true;input(h.nodes.get('career-send-consent'));assert.equal(h.nodes.get('career-analyze').disabled,false);const p=click(h.nodes.get('career-analyze'));const check=all(h.nodes.get('career-jobs')).find(n=>n.tagName==='INPUT');check.checked=true;input(check);assert.equal(h.requests.at(-1).signal.aborted,true);h.requests.at(-1).resolve({reply:'STALE',settings:preview.settings,previewHash:preview.hash,revision:1,sources:[]});await p;assert.doesNotMatch(h.nodes.get('career-note-text').value,/STALE/);assert.equal(h.nodes.get('career-copy').disabled,true);await makePreview(h);h.career.settingsChanged();assert.equal(h.nodes.get('career-analyze').disabled,true);});
test('canceled refresh keeps previous successful evidence even if the response arrives',async()=>{const f=fixture();f.companies=[company];f.jobs=[job('j1')];const h=await loaded(f);const refresh=all(h.nodes.get('career-companies')).find(n=>n.textContent==='Refresh jobs');const p=click(refresh);await click(h.nodes.get('career-cancel'));assert.equal(h.requests.at(-1).signal.aborted,true);h.requests.at(-1).resolve({...f,jobs:[]});await p;assert.match(text(h.nodes.get('career-jobs')),/Software internship/);});
test('keys are write-only and cleared on both success and failure',async()=>{const h=await loaded();for(const fail of [true,false]){h.nodes.get('career-key').value='TEST-ONLY';const p=click(h.nodes.get('career-key-save'));assert.equal(h.requests.at(-1).body.key,'TEST-ONLY');assert.equal(h.nodes.get('career-key').value,'');if(fail)h.requests.at(-1).reject(new Error('Save failed'));else h.requests.at(-1).resolve({...fixture(),revision:2,keyConfigured:true});await p;assert.equal(h.nodes.get('career-key').value,'');}assert.doesNotMatch(text(h.nodes.get('career-usage')),/TEST-ONLY/);});
test('filters, literal source text, unknown listing and HTTPS links stay honest and bounded',async()=>{const f=fixture();f.companies=[company];f.jobs=Array.from({length:55},(_,i)=>job('j'+i));f.jobs[0]=job('j0',{title:'<img src=x onerror=alert(1)>',url:'javascript:alert(1)',text:'<script>literal</script>'});const h=await loaded(f);assert.equal(all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='ARTICLE').length,50);assert.match(text(h.nodes.get('career-jobs')),/<script>literal<\/script>/);assert.match(text(h.nodes.get('career-jobs')),/not a confirmed opening/i);assert.ok(all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='A').every(n=>n.href.startsWith('https:')&&n.rel==='noopener noreferrer'));h.nodes.get('career-title-filter').value='<img';input(h.nodes.get('career-title-filter'));assert.equal(all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='ARTICLE').length,1);h.nodes.get('career-location-filter').value='Tokyo';input(h.nodes.get('career-location-filter'));assert.equal(all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='ARTICLE').length,0);});
test('usage retains exact token strings and user-entered associations without ranks',async()=>{const f=fixture();f.companies=[{...company,modelPrefixes:['synthetic/']}];f.usage={rows:[{date:'2026-10-01',model:'synthetic/model',totalTokens:'900719925474099312345'}],asOf:'2026-10-02',startDate:'2026-09-25',endDate:'2026-10-01',version:'v1',fetchedAt:'2026-10-02T00:00:00Z',sourceUrl:'https://openrouter.ai/rankings'};const h=await loaded(f);const t=text(h.nodes.get('career-usage'));assert.match(t,/900719925474099312345/);assert.match(t,/CC BY 4.0/);assert.match(t,/as of 2026-10-02/);assert.match(t,/Synthetic AI.*user-entered/i);});
test('missing optional dataset and unsaved model settings never trigger a provider request',async()=>{const h=await loaded();h.setSettings(null);h.career.settingsChanged();await click(h.nodes.get('career-preview'));assert.equal(h.requests.length,1);assert.match(text(h.nodes.get('career-usage')),/No.*snapshot/i);assert.match(text(h.nodes.get('career-status')),/settings/i);});
test('Codex empty default copies exact reviewed messages and cannot auto-analyze',async()=>{const h=await loaded();h.setSettings({provider:'codex-cli',model:''});await makePreview(h,{...preview,delivery:'manual',settings:{provider:'codex-cli',model:''}});assert.equal(h.nodes.get('career-analyze').disabled,true);await click(h.nodes.get('career-analyze'));await click(h.nodes.get('career-copy'));assert.match(h.copied[0],/Exact system/);assert.match(h.copied[0],/Exact reviewed context/);assert.equal(h.requests.length,2);});
test('student edits invalidate preview and inclusion remains explicitly opt-in',async()=>{const h=await loaded();await makePreview(h);assert.equal(h.requests[1].body.selection.includeStudent,false);h.nodes.get('career-student-skills').value='TypeScript';input(h.nodes.get('career-student-skills'));assert.equal(h.nodes.get('career-copy').disabled,true);await click(h.nodes.get('career-preview'));assert.equal(h.requests.length,2,'unsaved profile must not silently preview a saved profile');});
test('deleting a company invalidates pending preview and late context cannot enable sending',async()=>{const f=fixture();f.companies=[company];const h=await loaded(f);const p=click(h.nodes.get('career-preview'));await click(all(h.nodes.get('career-companies')).find(n=>n.textContent==='Delete company'));const d=click(h.nodes.get('career-delete-confirm'));h.requests[2].resolve({...fixture(),revision:2});await d;h.requests[1].resolve(preview);await p;assert.equal(h.nodes.get('career-copy').disabled,true);assert.equal(h.requests[2].method,'DELETE');assert.deepEqual(JSON.parse(JSON.stringify(h.requests[2].body)),{revision:1});});


test('preview compares settings semantically and manual copy never exposes CLI paths',async()=>{const h=await loaded();h.setSettings({provider:'codex-cli',endpoint:'',model:'',localConfirmed:false,cliPath:'/private/account-cli',cloudConfirmed:false});await makePreview(h,{...preview,delivery:'manual',settings:{cloudConfirmed:false,cliPath:'/private/account-cli',localConfirmed:false,model:'',endpoint:'',provider:'codex-cli'}});await click(h.nodes.get('career-copy'));assert.equal(h.copied.length,1);assert.doesNotMatch(h.copied[0],/private|cliPath|settings/);});
test('six evidence maximum and native filters include level and workplace',async()=>{const f=fixture();f.companies=[company];f.jobs=Array.from({length:7},(_,i)=>job('j'+i));const h=await loaded(f);for(const check of all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='INPUT')){check.checked=true;input(check);}assert.match(text(h.nodes.get('career-selection-count')),/6 \/ 6/);assert.equal(all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='INPUT').at(-1).checked,false);h.nodes.get('career-level-filter').value='new-graduate';input(h.nodes.get('career-level-filter'));assert.equal(all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='ARTICLE').length,0);h.nodes.get('career-level-filter').value='';h.nodes.get('career-remote-filter').value='on-site';input(h.nodes.get('career-remote-filter'));assert.equal(all(h.nodes.get('career-jobs')).filter(n=>n.tagName==='ARTICLE').length,0);});
test('aggregate other cannot be associated even with a matching user prefix',async()=>{const f=fixture();f.companies=[{...company,modelPrefixes:['other']}];f.usage={rows:[{date:'2026-10-01',model:'other',totalTokens:'10'}],fetchedAt:'2026-10-02',sourceUrl:'https://openrouter.ai/rankings'};const h=await loaded(f);assert.match(text(h.nodes.get('career-usage')),/Aggregate other; no employer association/);assert.doesNotMatch(text(h.nodes.get('career-usage')),/Synthetic AI/);});

test('Claude default model sends only the reviewed payload and leaves the response unsaved',async()=>{const h=await loaded();const cli={provider:'claude-cli',model:'',endpoint:'',localConfirmed:false,cloudConfirmed:true};h.setSettings(cli);await makePreview(h,{...preview,settings:cli});await click(h.nodes.get('career-analyze'));assert.equal(h.requests.length,2,'consent is required for every preview');h.nodes.get('career-send-consent').checked=true;input(h.nodes.get('career-send-consent'));const p=click(h.nodes.get('career-analyze'));assert.deepEqual(JSON.parse(JSON.stringify(h.requests[2].body)),{revision:1,selection:{jobIds:[],updateIds:[],includeStudent:false,question:''},previewHash:'preview-1',settings:cli});h.requests[2].resolve({revision:1,reply:'<script>unsaved advice</script>',sources:[],settings:cli,previewHash:'preview-1'});await p;assert.equal(h.nodes.get('career-note-text').value,'<script>unsaved advice</script>');assert.equal(h.requests.length,3);h.nodes.get('career-note-text').value='Edited note';const save=click(h.nodes.get('career-note-save'));assert.equal(h.requests[3].url,'/api/career/advice');assert.equal(h.requests[3].body.text,'Edited note');h.requests[3].resolve({...fixture(),revision:2,advice:[{id:'n1',text:'Edited note',createdAt:'2026-10-03',provider:'claude-cli',model:'',sources:[]}]});await save;assert.match(text(h.nodes.get('career-notes')),/Saved note/);});
test('student save uses PUT and opt-in is included only after explicit selection',async()=>{const h=await loaded();h.nodes.get('career-student-stage').value='Final year';input(h.nodes.get('career-student-stage'));const p=click(h.nodes.get('career-student-save'));assert.equal(h.requests[1].method,'PUT');assert.equal(h.requests[1].body.student.stage,'Final year');h.requests[1].resolve({...fixture(),revision:2,student:{...fixture().student,stage:'Final year'}});await p;h.nodes.get('career-include-student').checked=true;input(h.nodes.get('career-include-student'));await makePreview(h,{...preview,revision:2});assert.equal(h.requests[2].body.selection.includeStudent,true);});
test('editable examples and paste perform only explicit local saves with exact DTO fields',async()=>{const h=await loaded();await click(h.nodes.get('career-examples'));assert.equal(h.requests.length,1);assert.equal(h.nodes.get('career-company-careers').value,'https://jobs.ashbyhq.com/mistral.ai');h.nodes.get('career-example').value='3';input(h.nodes.get('career-example'));assert.equal(h.nodes.get('career-company-news').value,'https://openai.com/news/rss.xml');const p=click(h.nodes.get('career-company-save'));assert.deepEqual(Object.keys(h.requests[1].body.company).sort(),['careersUrl','id','modelPrefixes','name','newsUrls','website']);h.requests[1].resolve({...fixture(),revision:2,companies:[company]});await p;await click(h.nodes.get('career-paste-update'));h.nodes.get('career-paste-name').value='Evidence';h.nodes.get('career-paste-text').value='User-reviewed excerpt';const paste=click(h.nodes.get('career-paste-save'));assert.deepEqual(JSON.parse(JSON.stringify(h.requests[2].body)),{revision:2,companyId:'c1',kind:'updates',title:'Evidence',url:'',text:'User-reviewed excerpt'});h.requests[2].resolve({...fixture(),revision:3,companies:[company]});await paste;});
test('source success samples and date-only metadata remain literal',async()=>{const f=fixture();f.companies=[{...company,refreshes:[{kind:'updates',sourceUrl:'https://example.com/feed',checkedAt:'2026-10-03T00:00:00Z',lastSuccess:'2026-10-03T00:00:00Z',error:'',complete:false}]}];f.updates=[{id:'u1',companyId:'c1',title:'Update',kind:'rss',text:'Excerpt',url:'https://example.com/article',sourceUrl:'https://example.com/feed',publishedAt:'2026-10-01',fetchedAt:'2026-10-03T00:00:00Z'}];const h=await loaded(f);assert.match(text(h.nodes.get('career-updates')),/published: 2026-10-01/);assert.doesNotMatch(text(h.nodes.get('career-updates')),/published: 2026-10-01T/);assert.match(text(h.nodes.get('career-updates')),/Successful bounded sample/);assert.doesNotMatch(text(h.nodes.get('career-updates')),/Failed/);});

test('saved company closes its dialog and restores focus after controls unlock',async()=>{const h=await loaded();await click(h.nodes.get('career-add-company'));h.nodes.get('career-company-name').value='Draft';const p=click(h.nodes.get('career-company-save'));h.requests[1].resolve({...fixture(),revision:2,companies:[company]});await p;assert.equal(h.nodes.get('career-company-dialog').open,false);assert.equal(h.nodes.get('career-add-company').focusedWhileDisabled,false);});

test('Escape closes a pending editor without allowing duplicate writes or losing a failed draft',async()=>{const h=await loaded();await click(h.nodes.get('career-add-company'));h.nodes.get('career-company-name').value='Keep draft';const p=click(h.nodes.get('career-company-save'));h.nodes.get('career-company-dialog').oncancel({preventDefault(){}});assert.equal(h.nodes.get('career-company-dialog').open,false);assert.match(text(h.nodes.get('career-status')),/continues/i);await click(h.nodes.get('career-company-save'));assert.equal(h.requests.length,2);h.requests[1].reject(new Error('Save failed'));await p;assert.equal(h.nodes.get('career-company-name').value,'Keep draft');assert.match(text(h.nodes.get('career-status')),/Save failed/);assert.equal(h.nodes.get('career-add-company').disabled,false);});

test('complete-board disappearance uses the actual no-longer-listed DTO without claiming closure',async()=>{const f=fixture();f.companies=[company];f.jobs=[job('j1',{provider:'ashby',listingState:'no-longer-listed'})];const h=await loaded(f);assert.match(text(h.nodes.get('career-jobs')),/No longer listed on a complete board/);assert.match(text(h.nodes.get('career-jobs')),/not proof the role closed/);assert.doesNotMatch(text(h.nodes.get('career-jobs')),/Listing unknown/);});
test('reentry during canceled write waits for settlement then rereads the local revision',async()=>{const f=fixture();f.companies=[company];const h=await loaded(f);const refresh=all(h.nodes.get('career-companies')).find(n=>n.textContent==='Refresh jobs');const pending=click(refresh);h.career.leave();await h.career.enter();assert.equal(h.requests.length,2,'do not overlap the unsettled mutation');assert.match(text(h.nodes.get('career-status')),/waiting.*reload/i);h.requests[1].resolve({...f,revision:2});await pending;assert.equal(h.requests.length,3);assert.equal(h.requests[2].url,'/api/career');assert.equal(h.requests[2].method,'GET');h.requests[2].resolve({...f,revision:2});await new Promise(setImmediate);const p=click(refresh);assert.equal(h.requests[3].body.revision,2);h.requests[3].resolve({...f,revision:3});await p;});

test('analysis locks draft edits and saved-note copies until success or failure settles',async()=>{
  const f=fixture();f.advice=[{id:'n1',text:'Saved note',createdAt:'2026-10-03',provider:'ollama',model:'local',sources:[]}];
  const h=await loaded(f),draft=h.nodes.get('career-note-text');draft.value='Keep my draft';await makePreview(h);
  h.nodes.get('career-send-consent').checked=true;input(h.nodes.get('career-send-consent'));
  const edit=all(h.nodes.get('career-notes')).find(n=>n.textContent==='Edit in draft');
  const failed=click(h.nodes.get('career-analyze'));
  assert.equal(draft.disabled,true);assert.equal(edit.disabled,true);
  await click(edit);assert.equal(draft.value,'Keep my draft');
  h.requests.at(-1).reject(new Error('Analysis failed'));await failed;
  assert.equal(draft.value,'Keep my draft');assert.equal(draft.disabled,false);assert.equal(edit.disabled,false);
  const success=click(h.nodes.get('career-analyze'));assert.equal(draft.disabled,true);
  h.requests.at(-1).resolve({reply:'Reviewed answer'});await success;
  assert.equal(draft.value,'Reviewed answer');assert.equal(draft.disabled,false);assert.equal(edit.disabled,false);
});

test('local reload blocks mutations without clearing a key and enables saves at the new revision',async()=>{
  const f=fixture();f.companies=[company];const h=await loaded(f);
  const key=h.nodes.get('career-key');key.value='SYNTHETIC-TEST-KEY';
  const reload=h.career.enter(),refresh=all(h.nodes.get('career-companies')).find(n=>n.textContent==='Refresh jobs');
  assert.equal(h.nodes.get('career-key-save').disabled,true);assert.equal(refresh.disabled,true);assert.equal(h.nodes.get('career-note-save').disabled,true);
  await click(h.nodes.get('career-key-save'));assert.equal(key.value,'SYNTHETIC-TEST-KEY');assert.equal(h.requests.length,2);assert.match(text(h.nodes.get('career-status')),/reload|loading/i);
  await click(refresh);assert.equal(h.requests.length,2);
  h.requests[1].resolve({...f,revision:2});await reload;
  assert.equal(h.nodes.get('career-key-save').disabled,false);
  const save=click(h.nodes.get('career-key-save'));assert.equal(h.requests[2].body.key,'SYNTHETIC-TEST-KEY');assert.equal(h.requests[2].body.revision,2);assert.equal(key.value,'');
  h.requests[2].resolve({...f,revision:3,keyConfigured:true});await save;
});

test('usage displays the canonical OpenRouter snapshot attribution with its license link',async()=>{
  const f=fixture();f.usage={rows:[{date:'2026-10-01',model:'synthetic/model',totalTokens:'10'}],asOf:'2026-10-02T02:00:00Z',startDate:'2026-09-25',endDate:'2026-10-01',version:'v1',fetchedAt:'2026-10-02T02:01:00Z',sourceUrl:'https://openrouter.ai/rankings'};
  const h=await loaded(f),usage=h.nodes.get('career-usage');
  assert.match(text(usage),/Source: OpenRouter \(openrouter\.ai\/rankings\), as of 2026-10-02T02:00:00Z\. Licensed under CC BY 4\.0\./);
  assert.ok(all(usage).some(n=>n.tagName==='A'&&n.href==='https://creativecommons.org/licenses/by/4.0/'));
  assert.match(text(usage),/no market share or employer ranking/i);
});
